apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-app
  name: go-app
spec:
  type: NodePort # verificar types possiveis
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: go-app