apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  type: NodePort # verificar types possiveis
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: node-app